# Generated by Django 4.0.2 on 2022-02-07 18:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('getotp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 7, 18, 31, 31, 358842, tzinfo=utc)),
        ),
    ]
